application: vote4whatever
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: voting.app

libraries:
- name: jinja2
  version: latest